### ISSUE TITLE
Request for Support for Python 3.12 and Higher

### ISSUE THREAD

**Issue by TutuchanXD** [wcxve/elisa#129]
I noticed that the package currently supports up to Python 3.11. Do you have any plans to add support for Python 3.12 and higher versions?

**Comment by wcxve** [comment]
Hi, thank you for your interest in ELISA!

Support for Python 3.12+ mainly depends on the ELISA dependencies' compatibility with Python 3.12+. After a quick test, we found that the source code successfully passes all unit tests in a Python 3.12 environment without any modifications. This means Python 3.12 is indeed supported and will be added to the list of supported versions once comprehensive testing is complete. Python 3.13+ will also be added as soon as all dependencies are compatible.
